[package]
name = "day-2023-05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day-2023-05-part1"
path = "src/bin/part1.rs"

[[bin]]
name = "day-2023-05-part2"
path = "src/bin/part2.rs"